#!/bin/bash
cmd 2>/dev/null

errorlist=""
error()
{
	errorlist="$errorlist $1"
}

clear
echo "=================="
echo -e "\e[5mBuilding...\e[25m"
echo "=================="
echo -ne "Cleaning up...\003\r\t\t\t"
bash cleanup
bash toolchain/prep
bash mvksrc
echo -ne "Incrementing version...\003\r\t\t\t"
cd toolchain/versionmanager
bash manager
echo "DONE"
cd ..
cd ..
echo -ne "Generating GRUB.cfg...\003\r\t\t\t"
bash config
echo "DONE"
echo -ne "Assembling boot.s...\003\r\t\t\t"
i686-elf-as src/boot.s -o build/boot.o
echo "DONE"
echo -ne "Compiling Kernel.c...\003\r\t\t\t"
i686-elf-gcc -c src/kernel.c -o build/kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
echo "DONE"
echo -ne "Linking...\003\r\t\t\t"
i686-elf-gcc -T linker.ld -o build/lhc.bin -ffreestanding -O2 -nostdlib build/boot.o build/kernel.o -lgcc
echo "DONE"
echo -e "Creating ISO..."
mkdir -p isodir
mkdir -p isodir/boot
cp build/lhc.bin isodir/boot/lhc.bin
mkdir -p isodir/boot/grub
cp grub.cfg isodir/boot/grub/grub.cfg
osname=$(head -n 1 os.cfg)
grub2-mkrescue -o $osname.iso isodir
echo "========"
echo "- DONE -"
echo "========"
echo "Errors:"
echo $errorlist
echo "========"

