#!/bin/bash
echo "============================"
echo "Downloading final scripts..."
echo "============================"
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/toolchain/prep
chmod a+x prep
cd ..
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/run
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/kbuild
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/linker.ld
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/grub.cfg
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/cleanup
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/config
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/bar
chmod a+x run
chmod a+x kbuild
chmod a+x cleanup
chmod a+x config
chmod a+x bar
cd toolchain
mkdir versionmanager
cd versionmanager
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/toolchain/versionmanager/manager
cd ..
cd ..
echo "==========================="
echo "Downloading HADRON..."
echo "==========================="
mkdir ksrc
cd ksrc
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/ksrc/kernel.c
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/ksrc/boot.s
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/ksrc/terminal.h
wget https://raw.githubusercontent.com/JoshMiles/SOXS2/master/SOXS/ksrc/stdio.h


echo "==========================="
echo "Configure LHC..."
echo "==========================="
cd ..
bash config -c
cd toolchain/versionmanager
bash manager
cd ..
cd ..
echo "==========================="
echo "Setup complete."
echo "==========================="
